"""add overnight carry learning fields

Revision ID: 0aa83b95c713
Revises: 0c3e7a9f1b24
"""

from alembic import op
import sqlalchemy as sa


revision = "0aa83b95c713"
down_revision = "0c3e7a9f1b24"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "trade_journals",
        sa.Column(
            "carry_evaluated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "carry_state",
            sa.String(length=32),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "carry_decision",
            sa.String(length=64),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "carry_threatened_side",
            sa.String(length=16),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "carry_short_cushion",
            sa.Float(),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "carry_expected_move",
            sa.Float(),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "carry_expected_move_source",
            sa.String(length=32),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "carry_cushion_ratio",
            sa.Float(),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "carry_vix1d",
            sa.Float(),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "carry_vix",
            sa.Float(),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "carry_snapshot",
            sa.JSON(),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "held_overnight",
            sa.Boolean(),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "next_open_evaluated_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "next_open_spx",
            sa.Float(),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "next_open_gap_points",
            sa.Float(),
            nullable=True,
        ),
    )
    op.add_column(
        "trade_journals",
        sa.Column(
            "next_open_short_breached",
            sa.Boolean(),
            nullable=True,
        ),
    )


def downgrade():
    op.drop_column(
        "trade_journals",
        "next_open_short_breached",
    )
    op.drop_column(
        "trade_journals",
        "next_open_gap_points",
    )
    op.drop_column(
        "trade_journals",
        "next_open_spx",
    )
    op.drop_column(
        "trade_journals",
        "next_open_evaluated_at",
    )
    op.drop_column(
        "trade_journals",
        "held_overnight",
    )
    op.drop_column(
        "trade_journals",
        "carry_snapshot",
    )
    op.drop_column(
        "trade_journals",
        "carry_vix",
    )
    op.drop_column(
        "trade_journals",
        "carry_vix1d",
    )
    op.drop_column(
        "trade_journals",
        "carry_cushion_ratio",
    )
    op.drop_column(
        "trade_journals",
        "carry_expected_move_source",
    )
    op.drop_column(
        "trade_journals",
        "carry_expected_move",
    )
    op.drop_column(
        "trade_journals",
        "carry_short_cushion",
    )
    op.drop_column(
        "trade_journals",
        "carry_threatened_side",
    )
    op.drop_column(
        "trade_journals",
        "carry_decision",
    )
    op.drop_column(
        "trade_journals",
        "carry_state",
    )
    op.drop_column(
        "trade_journals",
        "carry_evaluated_at",
    )
